from typing import Sequence

class GcRef: ...

def get_typeids_z() -> bytes: ...
def get_typeids_list() -> Sequence[int]: ...
def get_rpy_type_index(obj: object) -> int: ...
def get_rpy_referents(obj: object) -> Sequence[object]: ...
