os: linux
language: python
dist: focal

jobs:
  include:
    # The pypy tests are slow, so we list them first
    - python: pypy3.6-7.2.0
      dist: bionic
    - language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.6
    # Disabled until Trio works:
    #- language: generic
    #  env: PYPY_NIGHTLY_BRANCH=py3.7
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    - python: 3.9-dev
    - python: 3.10-dev

script:
  - ./ci.sh

branches:
  only:
    - master
